- name: Ensure net.ipv4.ip_forward=1 is set in /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#?net\.ipv4\.ip_forward'
    line: 'net.ipv4.ip_forward=1'
    state: present
    backrefs: yes

- name: Ensure net.ipv6.conf.all.disable_ipv6=1 is set in /etc/sysctl.conf (optional)
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#?net\.ipv6\.conf\.all\.disable_ipv6'
    line: 'net.ipv6.conf.all.disable_ipv6=1'
    state: present
    backrefs: yes
  ignore_errors: yes

- name: Apply sysctl settings
  command: sysctl -p

- name: Preseed iptables-persistent for IPv4
  ansible.builtin.shell: echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
  become: yes

- name: Preseed iptables-persistent for IPv6
  ansible.builtin.shell: echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections
  become: yes

- name: Install iptables-persistent non-interactively
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: yes
    install_recommends: no
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set up NAT for routing from br0 to WAN
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: enp1s0f0
    source: 10.10.10.0/24
    jump: MASQUERADE
    state: present
  register: nat_rule

- name: Allow DNS queries to dnsmasq (UDP)
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: br0
    protocol: udp
    destination_port: 53
    jump: ACCEPT
    state: present

- name: Allow DNS queries to dnsmasq (TCP)
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: br0
    protocol: tcp
    destination_port: 53
    jump: ACCEPT
    state: present

- name: Allow DHCP traffic (UDP 67)
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: br0
    protocol: udp
    destination_port: 67
    jump: ACCEPT
    state: present

- name: Allow DHCP traffic (UDP 68)
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: br0
    protocol: udp
    destination_port: 68
    jump: ACCEPT
    state: present

- name: Allow DNS forwarding (UDP)
  ansible.builtin.iptables:
    chain: OUTPUT
    out_interface: enp1s0f0
    protocol: udp
    destination_port: 53
    jump: ACCEPT
    state: present

- name: Allow DNS forwarding (TCP)
  ansible.builtin.iptables:
    chain: OUTPUT
    out_interface: enp1s0f0
    protocol: tcp
    destination_port: 53
    jump: ACCEPT
    state: present

- name: Save iptables rules with netfilter-persistent
  ansible.builtin.shell: netfilter-persistent save
  become: yes
  changed_when: nat_rule.changed