- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Deploy dnsmasq configuration
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dnsmasq

- name: Include TFTP/iPXE setup
  ansible.builtin.include_tasks: tftp_ipxe.yml

- name: Ensure dnsmasq is enabled and started
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: yes
    state: started

- name: Configure systemd-resolved to work with dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: 'DNS=127.0.0.1'
    state: present
    backup: yes

- name: Configure systemd-resolved domains for .home
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?Domains='
    line: 'Domains=~home'
    state: present

- name: Disable systemd-resolved stub listener to avoid port 53 conflicts
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener='
    line: 'DNSStubListener=no'
    state: present

- name: Restart systemd-resolved with new configuration
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: yes