- name: Install Python pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install Docker Python library
  ansible.builtin.pip:
    name: docker
    state: present

- name: Install community.docker Ansible collection
  ansible.builtin.command:
    cmd: ansible-galaxy collection install community.docker
  register: collection_install
  changed_when: "'Nothing to do' not in collection_install.stdout"

- name: Show collection installation result
  debug:
    var: collection_install.stdout