- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install required packages for Docker
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt cache after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop:
    - piyer
    - root

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

